[package]
name = "netbricks"
version = "0.3.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>", "William of Ockham <williamofockham@gmail.com>"]
build = "build.rs"

[lib]
doctest = false

[dependencies]
byteorder = "*"
clippy = { version = ">=0.0.197", optional = true }
crossbeam = "=0.4"
enum_primitive = "0.1.1"
failure = "0.1.5"
fallible-iterator = "0.2.0"
fnv = "*"
generic-array = ">=0.11.0"
getopts = "*"
hex = "0.3.2"
lazy_static = "*"
libc = ">= 0.2.4"
log = { version = "0.4", features = ["std", "serde"]}
net2 = "*"
# NIX restricts us to just unix for now, we can fix this if someone cares at a later point.
nix = "*"
num = "0.1"
num-derive="0.2"
num-traits = "0.2"
rayon = "1.0.3"
regex = "*"
rust-sctp = { git="https://github.com/netsys/rust-sctp", optional = true}
serde = "1.0"
serde_derive = "1.0"
time = ">=0.1.0"
toml = "*"
twox-hash = "*"
uuid = { version = "*", features = ["v4"] }

[features]
default = []
performance = []
dev = ["clippy"]
packet_offset = []
sctp = ["rust-sctp"]

[build-dependencies]
# Use Bindgen to generate DPDK structures.
bindgen = "0.35.0"
