[package]
name = "acl-fw"
version = "0.1.0"
authors = ["Aurojit Panda <apanda@cs.berkeley.edu>"]

[dependencies]
netbricks = { path = "../../framework"}
time = ">=0.1.0"
getopts = "*"
rand = "0.3"
fnv = "*"
twox-hash = "*"
lazy_static = "*"

[features]
default = []
print = []
